### PR TITLE
Support python < 3.10

### PR DESCRIPTION
**Pull request by lez**
I use your python module both for my nsite project and a git remote helper. (https://github.com/lez/nsite and https://github.com/lez/git-remote-nostr) I'm very gateful that monstr exists. It's the only async python nostr module that I found.
So I'd like my users to be able to use the tools I develop on slightly outdated computers (and... on my server).
For this reason I reverted the `|`'s to `Union[...]` because it gave me `SyntaxError`s on older python versions.

On top, there are a few typos fixed.

### CODE REVIEW

**Comment by monty888** [comment]
This looks good. Once I've had chance to give it a try I'll merge it.

**Comment by lez** [comment]
Do you have plans releasing a new version with the fixes?

**Comment by monty888** [comment]
Hi I think I already did. The latest release here and on pypy if you install via pip should both include this change.

**Comment by lez** [comment]
Sorry, dunno what I was looking at... Its released, indeed.

**Pull request merged**
